avisosradio/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function () {
    return view('welcome'); //Usuarios invitados
});

Route::auth(); //Rutas de autenticación

Route::get('/home', 'HomeController@index'); //Usuario ya logueados

/*Route::get('/secretaria', function(){
  return view('secretaria.secretaria');
});*/

Route::get('/locutor', function(){
  return view('locutor.locutor');
});

Route::get('/clientenuevo', function(){
  return view('secretaria.nuevoCliente');
});

/*Route::get('/listaavisos', function(){
  return view('secretaria.listaAvisos');
});*/
//Direcciones CRUD
Route::resource('cliente', 'ClienteController');
Route::resource('aviso', 'AvisoController');
Route::resource('editaAviso', 'editaAvisoController');

Route::resource('alquiler', 'AvisoController@avisoSinLeer1');
Route::resource('solicitado', 'AvisoController@avisoSinLeer2');
Route::resource('ofrecido', 'AvisoController@avisoSinLeer3');
Route::resource('venta', 'AvisoController@avisoSinLeer4');
Route::resource('compra', 'AvisoController@avisoSinLeer5');

//******MIS RUTAS
Route::get('/prueba', function () {
    return view('prueba');
});

avisosradio/resources/views/secretaria/editaAviso.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Secretaria</div>

                <div class="panel-body contenedor" align="center" style="padding: 0px 0px 0px 0px;">
                  <div class="row">
                    <div class="col-md-4">
                      <div class="list-group">
                        <a href="{{ url('/cliente') }}" class="list-group-item">Nuevo aviso</a>
                        <a href="{{ url('/clientenuevo') }}" class="list-group-item">Nuevo cliente</a>
                        <a href="{{ url('/aviso') }}" class="list-group-item active">Todos los avisos</a>
                      </div>
                    </div>
                    <div class="col-md-8">
                      @if($errors->has())
                          <div class='alert alert-danger'>
                              @foreach ($errors->all('<p>:message</p>') as $message)
                                  {!! $message !!}
                              @endforeach
                          </div>
                      @endif
                      {!! Form::model($aviso, array('route' => ['aviso.update', $aviso->id], 'method' => 'PUT')) !!}
                      <div class="form-group selection">
                        {!! Form::label('Clase:') !!}
                        {{ Form::select('clase', ['Alquiler' => 'Alquiler', 'Oficio solicitado' => 'Oficio solicitado', 'Oficio ofrecido' => 'Oficio ofrecido', 'Venta' => 'Venta', 'Compra' => 'Compra'],null, ['class' => 'form-control']) }}
                      </div>
                      <div class="form-group selection">
                        {!! Form::label('Tipo:') !!}
                        <!--
                          A = 20 palabras 5bs
                          B = 35 palabras 8bs
                          C = 45 palabras 10bs
                        -->
                        {{ Form::select('tipo', ['A' => 'A (5 Bs.)', 'B' => 'B (8 Bs.)', 'C' => 'C (10 Bs.)'], null, ['class' => 'form-control']) }}
                      </div>
                      <div class="form-group selection">
                        {!! Form::label('Cliente: ') !!}
                        <select class="form-control" name="id_cliente">
                          @foreach($clientes as $cliente)
                            @if($cliente->id == $aviso->id_cliente)
                            <option value="{{$cliente->id}}" selected>{{$cliente->nombres}} {{$cliente->apellidos}}</option>
                            @else
                            <option value="{{$cliente->id}}">{{$cliente->nombres}} {{$cliente->apellidos}}</option>
                            @endif
                          @endforeach
                        </select>
                      </div>
                      <div class="form-group">
                        {!! Form::label('Descripción: ') !!}
                        {{ Form::textarea('descripcion', null, ['placeholder'=>'Insertar descripción del aviso', 'class' => 'form-control']) }}
                      </div>
                      <div class="form-group">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                      </div>
                      {!! Form::close() !!}
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

avisosradio/resources/views/secretaria/listaavisos.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Secretaria</div>

                <div class="panel-body contenedor" align="center" style="padding: 0px 0px 0px 0px;">
                  <div class="row">
                    <div class="col-md-4">
                      <div class="list-group">
                        <a href="{{ url('/cliente') }}" class="list-group-item">Nuevo aviso</a>
                        <a href="{{ url('/clientenuevo') }}" class="list-group-item">Nuevo cliente</a>
                        <a href="{{ url('/aviso') }}" class="list-group-item active">Todos los avisos</a>
                      </div>
                    </div>
                    <div class="col-md-8">
                      @if (Session::has('message'))
                         <div class="alert alert-success">{{ Session::get('message') }}</div>
                      @endif
                      <div class='table-responsive'>
                          <table class='table table-striped table-bordered table-hover table-condensed'>
                            <thead>
                              <tr>
                                <th>Clase</th>
                                <th>Tipo</th>
                                <th>Descripción</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                              </tr>
                            </thead>
                            <tbody>
                              @foreach($avisos as $aviso)
                              <tr>
                                <td>{{$aviso->clase}}</td>
                                <td>{{$aviso->tipo}}</td>
                                <td>{{$aviso->descripcion}}</td>
                                <td>
                                    {{link_to_route('aviso.edit', $title = 'Editar', $parameters = $aviso->id, $attributes = array('class' => 'btn btn-success'))}}
                                </td>
                                <td>
                                    {{Form::open(['route'=>['aviso.destroy', $aviso->id], 'method'=>'DELETE'])}}
                                      {{Form::submit('Eliminar', ['class'=>'btn btn-danger'])}}
                                    {{Form::close()}}
                                </td>
                              </tr>
                              @endforeach
                            </tbody>
                          </table>
                        </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

avisosradio/resources/views/secretaria/nuevoCliente.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Secretaria</div>

                <div class="panel-body contenedor" align="center" style="padding: 0px 0px 0px 0px;">
                  <div class="row">
                    <div class="col-md-4">
                      <div class="list-group">
                        <a href="{{ url('/cliente') }}" class="list-group-item">Nuevo aviso</a>
                        <a href="{{ url('/clientenuevo') }}" class="list-group-item active">Nuevo cliente</a>
                        <a href="{{ url('/aviso') }}" class="list-group-item">Todos los avisos</a>
                      </div>
                    </div>
                    <div class="col-md-8">
                      @if (Session::has('message'))
                         <div class="alert alert-success">{{ Session::get('message') }}</div>
                      @endif
                      @if($errors->has())
                          <div class='alert alert-danger'>
                              @foreach ($errors->all('<p>:message</p>') as $message)
                                  {!! $message !!}
                              @endforeach
                          </div>
                      @endif
                      {!! Form::open(array('route' => 'cliente.store', 'method' => 'POST')) !!}
                        <div class="form-group">
                          {!! Form::label('Nombres:') !!}
                          {!! Form::text('nombres', null, ['class'=>'form-control', 'placeholder'=>'Nombre de cliente']) !!}
                        </div>
                        <div class="form-group">
                          {!! Form::label('Apellidos:') !!}
                          {!! Form::text('apellidos', null, ['class'=>'form-control', 'placeholder'=>'Apellidos de cliente']) !!}
                        </div>
                        <div class="form-group">
                          {!! Form::label('Ci:') !!}
                          {!! Form::text('ci', null, ['class'=>'form-control', 'placeholder'=>'Ci de cliente']) !!}
                        </div>
                        <div class="form-group">
                          {!! Form::label('Procedencia:') !!}
                          {!! Form::text('procedencia', null, ['class'=>'form-control', 'placeholder'=>'Procedencia ci']) !!}
                        </div>
                        <div class="form-group">
                          {!! Form::label('Nit:') !!}
                          {!! Form::text('nit', null, ['class'=>'form-control', 'placeholder'=>'Nit cliente']) !!}
                        </div>
                        <div class="form-group">
                          {!! Form::submit('Aceptar', ['class'=>'btn btn-primary']) !!}
                        </div>
                      {!! Form::close() !!}
                    </div>
                  </div>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

avisosradio/resources/views/secretaria/secretaria.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Secretaria</div>

                <div class="panel-body contenedor" align="center" style="padding: 0px 0px 0px 0px;">
                  <div class="row">
                    <div class="col-md-4">
                      <div class="list-group">
                        <a href="{{ url('/cliente') }}" class="list-group-item active">Nuevo aviso</a>
                        <a href="{{ url('/clientenuevo') }}" class="list-group-item">Nuevo cliente</a>
                        <a href="{{ url('/aviso') }}" class="list-group-item">Todos los avisos</a>
                      </div>
                    </div>
                    <div class="col-md-8">
                      @if (Session::has('message'))
                         <div class="alert alert-success">{{ Session::get('message') }}</div>
                      @endif
                      @if($errors->has())
                          <div class='alert alert-danger'>
                              @foreach ($errors->all('<p>:message</p>') as $message)
                                  {!! $message !!}
                              @endforeach
                          </div>
                      @endif
                      {!! Form::open(array('route' => 'aviso.store', 'method' => 'POST')) !!}
                      <div class="form-group selection">
                        {!! Form::label('Clase:') !!}
                        {{ Form::select('clase', ['Alquiler' => 'Alquiler', 'Oficio solicitado' => 'Oficio solicitado', 'Oficio ofrecido' => 'Oficio ofrecido', 'Venta' => 'Venta', 'Compra' => 'Compra'],null, ['class' => 'form-control']) }}
                      </div>
                      <div class="form-group selection">
                        {!! Form::label('Tipo:') !!}
                        <!--
                          A = 20 palabras 5bs
                          B = 35 palabras 8bs
                          C = 45 palabras 10bs
                        -->
                        {{ Form::select('tipo', ['A' => 'A (5 Bs.)', 'B' => 'B (8 Bs.)', 'C' => 'C (10 Bs.)'], null, ['class' => 'form-control']) }}
                      </div>
                      <div class="form-group selection">
                        {!! Form::label('Cliente: ') !!}
                        <select class="form-control" name="id_cliente">
                          @foreach($clientes as $cliente)
                          <option value="{{$cliente->id}}">{{$cliente->nombres}} {{$cliente->apellidos}}</option>
                          @endforeach
                        </select>
                      </div>
                      <div class="form-group">
                        {!! Form::label('Descripción: ') !!}
                        {{ Form::textarea('descripcion', null, ['placeholder'=>'Insertar descripción del aviso', 'class' => 'form-control']) }}
                      </div>
                      <div class="form-group">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                      </div>
                      {!! Form::close() !!}
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection