avisosradio/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function () {
    return view('welcome'); //Usuarios invitados
});

Route::auth(); //Rutas de autenticación

Route::get('/home', 'HomeController@index'); //Usuario ya logueados

/*Route::get('/secretaria', function(){
  return view('secretaria.secretaria');
});*/

Route::get('/locutor', function(){
  return view('locutor.locutor');
});

Route::get('/clientenuevo', function(){
  return view('secretaria.nuevoCliente');
});

/*Route::get('/listaavisos', function(){
  return view('secretaria.listaAvisos');
});*/
//Direcciones CRUD
Route::resource('cliente', 'ClienteController');
Route::resource('aviso', 'AvisoController');
Route::resource('editaAviso', 'editaAvisoController');

Route::resource('alquiler', 'AvisoController@avisoSinLeer1');
Route::resource('solicitado', 'AvisoController@avisoSinLeer2');
Route::resource('ofrecido', 'AvisoController@avisoSinLeer3');
Route::resource('venta', 'AvisoController@avisoSinLeer4');
Route::resource('compra', 'AvisoController@avisoSinLeer5');

//******MIS RUTAS
Route::get('/prueba', function () {
    return view('prueba');
});

avisosradio/resources/views/locutor/locutor.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Locutor</div>

                <div class="panel-body contenedor" align="center" style="padding: 0px 0px 0px 0px;">
                  <div class="row">
                    <div class="col-md-4">
                      <div class="list-group">
                        <a href="{{ url('/alquiler') }}" class="list-group-item {{$estadoMenu1}}">Alquiler</a>
                        <a href="{{ url('/solicitado') }}" class="list-group-item {{$estadoMenu2}}">Oficio solicitado</a>
                        <a href="{{ url('/ofrecido') }}" class="list-group-item {{$estadoMenu3}}">Oficio ofrecido</span></a>
                        <a href="{{ url('/venta') }}" class="list-group-item {{$estadoMenu4}}">Venta</a>
                        <a href="{{ url('/compra') }}" class="list-group-item {{$estadoMenu5}}">Compra</a>
                      </div>
                    </div>
                    <div class="col-md-8">
                      @if (Session::has('message'))
                         <div class="alert alert-success">{{ Session::get('message') }}</div>
                      @endif
                      <div class="list-group">
                        @foreach($avisosNuevos as $avisosNuevo)
                        <a href="#" class="list-group-item">
                          <h4 class="list-group-item-heading">Tipo: {{$avisosNuevo->tipo}}</h4>
                          <p class="list-group-item-text">{{$avisosNuevo->descripcion}}
                            {{link_to_route('editaAviso.edit', $title = 'Leer', $parameters = $avisosNuevo->id, $attributes = array('class' => 'btn btn-success'))}}
                          </p>
                        </a>
                        @endforeach
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection